(lang dune 3.24)

(name ptr_of_wii)

(generate_opam_files true)

(source
 (github virajsazzala/ptr_of_wii))

(authors "Viraj Reddy SNG <vir200319@gmail.com>")

(maintainers "Viraj Reddy SNG <vir200319@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name ptr_of_wii)
 (synopsis "wiimote as point and click device")
 (description "helps use wiimote as a point and click device")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
